import { Metadata } from "next";

// Task Details:

// You are to implement the two pages provided on the figma design here
// The register page has a slider that is to display the images attached by the side and also the Bootcamp Sales Page. Note that all screens must be very responsive as well.
// Deadline for submission is Saturday, 11th of October 2024 at 10pm
// The core framework or technologies to be used is Typescript and Next.js

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="flex flex-col justify-center items-center min-h-screen p-20 gap-16 sm:p-20 ">
      <h1 className="text-4xl font-bold ">Foundation of Android Development</h1>
      <p className="text-2xl font-jakarta">Coding Assessment</p>
    </div>
  );
}
